//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VEMCUCtl.rc
//
#define IDC_DELETENAME                  3
#define IDD_VEMCUCTL_DIALOG             102
#define INFO_TOOL                       103
#define IDB_BITMAP_TUNECYCLESETTING_OFF 105
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME1                  129
#define IDD_DIALOG_MENU                 130
#define IDD_DIALOG_LOGIN                131
#define IDB_BITMA_LOGIN                 132
#define IDD_DIALOG_PAGESERVER           133
#define IDD_DIALOG_VIEWOUT              136
#define IDC_CURSOR_YTDOWN_ON            137
#define IDC_CURSOR_YTDOWN               138
#define IDC_CURSOR_YTLEFT_ON            139
#define IDC_CURSOR_YTLEFT               140
#define IDC_CURSOR_YTRIGHT_ON           141
#define IDC_CURSOR_YTRIGHT              142
#define IDC_CURSOR_YTUP_ON              143
#define IDC_CURSOR_YTUP                 144
#define IDD_DIALOG_RECFILEPATH          150
#define IDD_DIALOG_REPLAY               151
#define IDB_BITMAP_QUERY                157
#define IDB_BITMAP_TOTAL_BG             158
#define IDB_BITMAP_PAGESERVER           161
#define IDI_TWENTYFIVEUP                162
#define IDI_FOURUP                      163
#define IDI_NINEUP                      164
#define IDI_ONEUP                       165
#define IDI_SIXTYUP                     166
#define IDB_BITMAP_RECORD               169
#define IDC_MY_HAND                     170
#define IDB_BITMAP_MENU_ELECMAP         171
#define IDB_BITMAP_MENU_MULTIVIEW       172
#define IDB_BITMAP_MENU_TUNECYCLE       173
#define IDB_BITMAP_MENU_LOG             174
#define IDB_BITMAP_MENU_REALTALK        175
#define IDB_BITMAP_MENU_FAVORITE        176
#define IDB_BITMAP_MENU_SYSSTRUCT       177
#define IDB_BITMAP_MENU_REPLAY          178
#define IDR_MENU_PAGESERVER_TREELIST    179
#define IDB_BITMAP_YT_CENTER            180
#define IDB_BITMAP_YT_DOWN              181
#define IDB_BITMAP_YT_LEFT              183
#define IDB_BITMAP_YT_PRESETCALL        185
#define IDB_BITMAP_YT_PRESETSAVE        186
#define IDB_BITMAP_YT_RESURVE2          188
#define IDB_BITMAP_YT_RIGHT             189
#define IDB_BITMAP_YT_UP                190
#define IDB_BITMAP_YT_ZOOMIN            191
#define IDB_BITMAP_YT_ZOOMOUT           192
#define IDB_BITMAP_TUNEPRE              193
#define IDB_BITMAP_SETPRE               194
#define IDB_BITMAP_VIEWSET              195
#define IDB_BITMAP_VIEWGET              196
#define IDB_BITMAP_CHOOSEVIEW_OFF       198
#define IDB_BITMAP_CHOOSEYT_OFF         200
#define IDB_BITMAP_TREE                 201
#define IDB_BITMAP_ON                   202
#define IDB_BITMAP_OFF                  203
#define IDB_BITMAP_DRAG                 204
#define IDR_MENU_MAINPOP                205
#define IDR_MENU_MAPMAIN                212
#define IDB_BITMAP_UPPAGE               213
#define IDB_BITMAP_DOWNPAGE             214
#define IDR_MENU_MAPVIDEO               215
#define IDR_MENU_TEMPFAVORITE           216
#define IDB_BITMAP_VIDEOSTOP            220
#define IDB_BITMAP_MENU_QUIT            229
#define IDB_BITMAP_BG_LEFTCORNER        230
#define IDB_BITMAP_BG_LEFTUPCORNER      231
#define IDB_BITMAP_BG_RIGHTCORNER       232
#define IDB_BITMAP_BG_RIGHTUPCORNER     233
#define IDB_BITMAP_BG_UPCORNER          234
#define IDB_BITMAP_MENU_LEFT            235
#define IDB_BITMAP_MENU_RIGHT           236
#define IDB_BITMAP_BG_BOTTOMLEFT        237
#define IDB_BITMAP_BG_BOTTMRIGHT        238
#define IDB_BITMAP_MENU_ALARMSET        240
#define IDB_BITMAP_BG_REPLAY            241
#define IDB_BITMAP_MENU_ALARMLOG        242
#define IDR_MENU_ADDTOSHIELD            243
#define IDR_MENU_DELETEFROMSHIELD       244
#define IDB_BITMAP_MENU_MIN             246
#define IDB_BITMAP_VIEWOUT_VOICE        247
#define IDB_BITMAP_VIEWOUT_VOICE_OPENED 248
#define IDB_BITMAP_VIEWOUT_CAPTURE      249
#define IDB_BITMAP_VIEWOUT_RECORD       250
#define IDB_BITMAP_VIEWOUT_RECORD_OPENED 251
#define IDB_BITMAP_MENU_NETSTRUCT       252
#define IDB_BITMAP_MENU_MAX             255
#define IDB_BITMAP_QUIT2                257
#define IDD_DIALOG_PRESET               259
#define IDD_DIALOG_VIDEOPARSET          260
#define IDB_BITMAP_CHOOSEPRESET         261
#define IDD_DIALOG_PRESET_NAME          262
#define IDB_BITMAP_DG_CLOSE             263
#define IDB_BITMAP_YS_OPEN              264
#define IDB_BITMAP_DG_OPEN              265
#define IDB_BITMAP_HW_CLOSE             266
#define IDB_BITMAP_HW_OPEN              267
#define IDB_BITMAP_JR_CLOSE             268
#define IDB_BITMAP_JR_OPEN              269
#define IDB_BITMAP_YS_CLOSE             270
#define IDD_DIALOG_HISTORYLOG           271
#define IDD_DIALOG_HISTORYLOG_RELATION  272
#define IDB_BITMAP_YT_CENTER_LOCK       274
#define IDB_BITMAP_PS_VIEWLIST_ON       278
#define IDB_BITMAP_PS_CAMERALIST_OFF    279
#define IDB_BITMAP_PS_CAMERALIST_ON     280
#define IDB_BITMAP_PS_CYCLELIST_OFF     281
#define IDB_BITMAP_PS_CYCLELIST_ON      282
#define IDB_BITMAP_PS_DEVICELIST_OFF    283
#define IDB_BITMAP_PS_DEVICELIST_ON     284
#define IDB_BITMAP_PS_VIEWLIST_OFF      285
#define IDR_MAIN                        295
#define IDB_BITMAP_BG_YT                297
#define IDB_BITMAP_CHOOSENODE           298
#define IDB_BITMAP_VIDEOTYPE            299
#define IDB_BITMAP_QUERYCONDITION       300
#define IDB_BITMAP_TIMEBEGINEND         301
#define IDB_BITMAP_QUERYRESULT          302
#define IDB_BITMAP_NOVIDEO              303
#define IDB_BITMAP_VIDEOPLAY            304
#define IDB_BITMAP_VIDEOFAST            305
#define IDB_BITMAP_VIDEOSLOW            306
#define IDB_BITMAP_PRESETLIST           308
#define IDB_BITMAP_PRESETCONFIG         309
#define IDB_BITMAP_PRESETBOTTOM         310
#define IDB_BITMAP_MODIFYPRESETNAME     311
#define IDB_BITMAP_DELPRESET            312
#define IDB_BITMAP_SETPRESET            313
#define IDB_BITMAP_ADDPRESETNAME        314
#define IDB_BITMAP_UPBG                 316
#define IDB_BITMAP_TUNECYCLE_TABTITLE   318
#define IDB_BITMAP_CHOOSEVIEW_ON        319
#define IDB_BITMAP_CHOOSEYT_ON          320
#define IDB_BITMAP_TUNECYCLESETTING_ON  321
#define IDB_BITMAP_TUNECYCLE            322
#define IDB_BITMAP_TUNECYCLEEXECUTE_ON  326
#define IDB_BITMAP_TUNECYCLEEXECUTE_OFF 327
#define IDB_BITMAP_TUNECYCLE_UPFRAME    328
#define IDB_BITMAP_TUNECYCLELIST        329
#define IDB_BITMAP_TUNECYCLESTATE       330
#define IDB_BITMAP_TUNECYCLEEND         331
#define IDB_BITMAP_TUNECYCLESTART       332
#define IDB_BITMAP_TUNECYCLE_CAMERALIST 333
#define IDB_BITMAP_SAVESETTING          334
#define IDB_BITMAP_MOVERIGHT            335
#define IDB_BITMAP_MOVELEFT             336
#define IDB_BITMAP_RELATIONINFO_LARGESHOW 337
#define IDB_BITMAP_PLAYER_BG            338
#define IDB_BITMAP_RP_UP_BG             341
#define IDB_BITMAP_RP_SEL_D5000_ON      342
#define IDB_BITMAP_RP_SEL_D5000_OFF     343
#define IDB_BITMAP_RP_SEL_OP_ON         344
#define IDB_BITMAP_RP_SEL_OP_OFF        345
#define IDB_BITMAP_RP_SEL_PT_ON         346
#define IDB_BITMAP_RP_SEL_PT_OFF        347
#define IDB_BITMAP_RP_SEL_WEATHER_ON    348
#define IDB_BITMAP_RP_SEL_WEATHER_OFF   349
#define IDB_BITMAP_HL_VIDEO_ON          350
#define IDB_BITMAP_HL_USER_ON           351
#define IDB_BITMAP_HL_SYSTEM_ON         352
#define IDB_BITMAP_HL_VIDEO_OFF         353
#define IDB_BITMAP_HL_USER_OFF          354
#define IDB_BITMAP_HL_SYSTEM_OFF        355
#define IDI_SIXUP                       356
#define IDR_MENU_PAGE_SERVER            357
#define IDR_MENU_TUNE_CYCLE             358
#define IDD_DIALOG_SELECT_DEVICE        359
#define IDB_BITMAP_SELECT               360
#define IDD_VIDEO_INFO_DIALOG           361
#define IDB_BITMAP_VIDEO_INFO_BK        362
#define IDR_MENU_SYSTEM_TRAY            363
#define IDB_BITMAP_USER_LOGIN           364
#define IDB_BITMAP_USER_CANCEL          365
#define IDB_BITMAP_SHOW_CONTROL         366
#define IDB_BITMAP_HIDE_CONTROL         367
#define IDB_BITMAP_SHOW_PAGESERVER      368
#define IDB_BITMAP_HIDE_PAGESERVER      369
#define IDB_BITMAP_LOGIN_EXIT           370
#define IDB_BITMAP_MENU_CENTER          371
#define IDB_BITMAP_MENU_MANAGE          372
#define IDB_BITMAP_SHOW_CONTROL2        373
#define IDD_DIALOG_SHOW_CONTROL         374
#define IDD_DIALOG_SHOW_PAGE_SERVER     375
#define IDB_BITMAP_SHOW_PAGE_SERVER     376
#define IDB_BITMAP_HIDE_PAGE_SERVER     377
#define IDB_BITMAP_PAGE_SERVER_BOTTOM   378
#define IDB_BITMAP_SELECT_NODE          379
#define IDB_BITMAP_QUERY_LOG            380
#define IDB_BITMAP_LOCAL_REPLAYER       381
#define IDB_BITMAP_NODE_SELECT          382
#define IDD_DIALOG_LINKAGE_SERVER       383
#define IDD_DIALOG_SHOW_LINKAGE_SERVER  384
#define IDB_BITMAP_SHOW_LINKAGE_SERVER  385
#define IDB_BITMAP_HIDE_LINKAGE_SERVER  386
#define IDB_BITMAP_EXTEND_LINKAGE       387
#define IDB_BITMAP_VIDEOPAUSE           388
#define IDB_BITMAP_SELECT_DEVICE_BK     389
#define IDB_BITMAP_ZOOMOUT              390
#define IDB_BITMAP_ZOOMIN               391
#define IDB_BITMAP_REPLAY_SLIDER_ON     392
#define IDB_BITMAP_REPLAY_SLIDER_OFF    393
#define IDB_BITMAP_REPLAY_SLIDER_THUMB_ON 394
#define IDB_BITMAP_REPLAY_SLIDER_THUMB_OFF 395
#define IDB_BITMAP_HL_RELATION_ON       396
#define IDB_BITMAP_HL_RELATION_OFF      397
#define IDD_DIALOG_HISTORYLOG_SYSTEM    398
#define IDD_DIALOG_HISTORYLOG_USER      399
#define IDD_DIALOG_HISTORYLOG_VIDEO_ERROR 400
#define IDB_BITMAP_VIEWOUT_FLAG_ALARM_LINKAGE 401
#define IDD_DIALOG_PICFILEPATH          401
#define IDB_BITMAP_VIEWOUT_FLAG_MANUAL_LINKAGE 402
#define IDB_BITMAP_VIEWOUT_FLAG_NORMAL  403
#define IDB_BITMAP_MENU_LOGIN           404
#define IDR_MENU_VIDEO_REPLAY           405
#define IDB_BITMAP_MENU_NAME            406
#define IDD_DIALOG_PAGE_VIEW_INFO       407
#define IDB_BITMAP_PREV_PAGE_BK         408
#define IDB_BITMAP_NEXT_PAGE_BK         409
#define IDB_BITMAP_EXPORT_REPORT_BK     410
#define IDB_BITMAP_REPORT_EXPORT_BK     412
#define IDB_BITMAP_CANCEL_BTN_BK        413
#define IDR_MENU_VIDEO_TAG              414
#define IDD_VIDEO_TAG_INFO_DIALOG       415
#define IDD_DIALOG_MODIFY_PASSWORD      416
#define IDB_BITMAP_MODIFY_PASSWORD_BK   417
#define IDB_BITMAP_MODIFY_PASSWORD_DLG_BG 418
#define IDB_BITMAP_MODIFY_BTN_BK        419
#define IDB_BITMAP_BTN_RECORD_REPORT_BK 420
#define IDB_BITMAP_RECORD_REPORT_EXPORT_BK 421
#define IDD_DIALOG_DEVICE_ONLINE_INFO   422
#define IDB_BITMAP_BTN_ONLINE_RATE      423
#define IDB_BITMAP_ONLINE_RATE_BG       424
#define IDB_BITMAP_BTN_HELP             425
#define IDD_DIALOG_TAG_CLASS            426
#define IDB_BITMAP_TAG_CLASS_BG         427
#define IDR_MENU_SELECT_DEVICE          428
#define IDD_DIALOG_SELECT_USER          429
#define IDB_BITMAP_SELECT_USER_BK       430
#define IDB_BITMAP_MENU_BOTTOM_BK       431
#define IDB_BITMAP_MENU_UP_BK           432
#define IDB_BITMAP_PAGESERVER_RIGHT_BK  433
#define IDB_BITMAP_VIEW_OUT_TOP_BK      434
#define IDB_BITMAP_VIEW_CHANNEL_BK      435
#define IDB_BITMAP_NORMAL_LINKAGE       439
#define IDB_BITMAP1                     440
#define IDB_BITMAP_DEVICE_REPORT_BK     440
#define IDB_BITMAP_LOGIN_SJ             441
#define IDB_BITMAP_MENU_SJ_RIGHT        442
#define IDB_BITMAP2                     443
#define IDB_BITMAP_BTN_SEARCH_NODE_BK   443
#define IDB_BITMAP_MENU_TRAY            444
#define IDD_DIALOG_PAGE_VIEW_SET_TIME   445
#define IDD_DIALOG_PAGEVIEW_SELECT      446
#define IDB_BITMAP_PAGEVIEW_SETTIME     447
#define IDB_BITMAP_SET_PAGEVIEW_TIME    448
#define IDB_BITMAP_CANCEL_PAGEVIEW_TIME 449
#define IDB_BITMAP_BTN_SET_TIME         450
#define IDB_BITMAP_BTN_PAUSE_PAGEVIEW   452
#define IDB_BITMAP_BTN_RESUME_PAGEVIEW  453
#define IDB_BITMAP_BTN_STOP_PAGEVIEW    454
#define IDB_BITMAP_PAGEVIEW_SELECT      455
#define IDB_BITMAP3                     456
#define IDB_BITMAP_BTN_START            456
#define IDD_DIALOG_CAMERA_STATUS        457
#define IDD_DIALOG_SHOW_ALARM           459
#define IDD_DIALOG_ALARM_INFO           460
#define IDD_DIALOG_DEVICE_LEDGER        461
#define IDD_DIALOG_STATION_SELECT       462
#define IDD_DIALOG_ALARM_SUBSCRIBE      463
#define IDD_DIALOG_HISTORYLOG_ALARM     464
#define IDD_DIALOG_HISTORYLOG_DEVICE    465
#define IDD_DIALOG_TREE_ELECMAP         466
#define IDD_DIALOG_LINKAGE_CONFIG       467
#define IDD_DIALOG_CAMERA_AND_CONTROL   468
#define IDD_DIALOG_DEVICE_RELATION_CAMERA 469
#define IDB_BITMAP_MENU_DEVICELEDGER    470
#define IDB_BITMAP4                     471
#define IDB_BITMAP_MENU_ASSVIEW         471
#define IDB_BITMAP_ALARM_REPLAY_OFF     475
#define IDB_BITMAP_ALARM_REPLAY_ON      476
#define IDB_BITMAP_SHOW_CONTROL3        477
#define IDD_DIALOG_ALARM_STATISTICS     478
#define IDD_DIALOG_ALARM_PREVIEW        479
#define IDD_DIALOG_COLUMN1              480
#define IDD_DIALOG_COLUMN2              481
#define IDD_DIALOG_STATION_ALARM        483
#define IDB_BITMAP_ALARM_PREVIEW        484
#define IDB_BITMAP_ALRAM_HISTORY_UNSEL  485
#define IDB_BITMAP_ALARM_HISTORY_SEL    486
#define IDB_BITMAP_DEVICE_DATA_UNSEL    487
#define IDB_BITMAP8                     488
#define IDB_BITMAP_DEVICE_DATA_SEL      488
#define IDC_MENU_EMAP                   1000
#define IDC_MENU_VIEW                   1001
#define IDC_MENU_TUNECYCLE              1002
#define IDC_MENU_EVENTLOG               1003
#define IDC_MENU_REALTALK               1004
#define IDC_MENU_TEMPFAVORITE           1005
#define IDC_TREE_SERVER                 1006
#define IDC_MENU_NETSTRUCT              1006
#define IDC_MENU_SYSTEM                 1007
#define IDC_TREE_TUNECYCLE              1007
#define IDC_MENU_MANAGE                 1008
#define IDC_TREE_PRESET                 1009
#define IDC_MENU_TRAFFIC                1010
#define IDC_MENU_MIN                    1011
#define IDC_MENU_TRAY                   1012
#define IDC_MENU_EXIT                   1013
#define IDC_BUTTON_LOGIN                1015
#define IDC_MENU_REPLAY                 1016
#define IDC_YT_ZOOMIN                   1018
#define IDC_EDIT_USER                   1019
#define IDC_YT_ZOOMOUT                  1020
#define IDC_EDIT_PASSWORD               1021
#define IDC_YT_SAVE                     1022
#define IDC_EDIT_NEW_PASSWORD           1022
#define IDC_YT_CALL                     1023
#define IDC_EDIT_NEW_PASSWORD2          1023
#define IDC_EDIT_USER2                  1024
#define IDC_YT_UP                       1025
#define IDC_STATIC_STATION              1026
#define IDC_YT_LEFT                     1027
#define IDC_STATIC_RELAINFO             1027
#define IDC_YT_DOWN                     1028
#define IDC_YT_RIGHT                    1029
#define IDC_BUTTON_HL_SYSTEM            1031
#define IDC_BUTTON_PS_FORM6             1031
#define IDC_BTN_EXIT                    1031
#define IDC_BTN_HIDE_LINKAGE_SERVER     1031
#define IDC_BTN_TYPE_FLAG               1031
#define IDC_MENU_LOGIN                  1031
#define IDC_BTN_PRE_PAGE                1031
#define IDC_BTN_MODIFY_PASSWORD         1031
#define IDC_BTN_OK                      1031
#define IDC_BUTTON_RP_D5000_SELECT      1032
#define IDC_BUTTON_HL_OPERATE           1032
#define IDC_BTN_EXIT2                   1032
#define IDC_BUTTON_RP_WEATHER_SELECT    1033
#define IDC_BUTTON_HL_RELATION          1033
#define IDC_BUTTON_SELECTID             1034
#define IDC_BUTTON_RP_OP_SELECT         1035
#define IDC_BUTTON_CAPTURE_VO           1036
#define IDC_BUTTON_D5000_STATION_SEL    1036
#define IDC_BUTTON_OP_STATION_SEL       1037
#define IDC_BUTTON_MODIFYNAME           1039
#define IDC_BUTTON_YS_OPEN              1040
#define IDC_BUTTON_RECORD_VO            1046
#define IDC_BUTTON_YS_CLOSE             1047
#define IDC_FILE                        1050
#define IDC_BUTTON_OPENVOICE_VO         1052
#define IDC_BUTTON_L_OPEN               1053
#define IDC_BUTTON_RS_SAVESETTING       1054
#define IDC_BUTTON_L_CLOSE              1056
#define IDC_BUTTON_PS_FORM16            1057
#define IDC_BUTTON_JR_OPEN              1062
#define IDC_BUTTON_HL_QUERY             1063
#define IDC_TAB_CYCLESELECT             1066
#define IDC_BUTTON_HW_OPEN              1069
#define IDC_BUTTON_JR_CLOSE             1075
#define IDC_BUTTON_HW_CLOSE             1077
#define IDC_YT_DIAPHRAGM_LARGE          1078
#define IDC_EXIT                        1080
#define IDC_BTN_EXPORT_REPORT           1080
#define IDC_BUTTON_PS_FORM1             1083
#define IDC_DATE_STARTDAY               1084
#define IDC_BUTTON_PS_FORM4             1086
#define IDC_BUTTON_PS_FORM9             1089
#define IDC_YT_DIAPHRAGM_SMALL          1091
#define IDC_BUTTON_PS_DEVICELIST        1095
#define IDC_DATE_STARTTIME              1096
#define IDC_BUTTON_PS_CYCLELIST         1097
#define IDC_BUTTON_PS_CAMERALIST        1100
#define IDC_YT_MODPRESET                1101
#define IDC_BUTTON_PS_CYCLE_LIST        1101
#define IDC_DATE_STOPDAY                1104
#define IDC_YT_SETMODPRESET             1104
#define IDC_MEMU_ALARMSET               1106
#define IDC_DATE_STOPTIME               1107
#define IDC_YT_RESURVE1                 1110
#define IDC_LIST_REPLAYFILE             1111
#define IDC_YT_RESURVE2                 1112
#define IDC_BUTTON_QUERY                1114
#define IDC_BUTTON_QUERY2               1115
#define IDC_BUTTON_LOCAL_REPLAY         1115
#define IDC_BUTTON_LOCALFILE            1118
#define IDC_RESULT_RECT                 1122
#define IDC_BUTTON_RELATION_SHOW        1123
#define IDC_CONDITION_RECT              1124
#define IDC_STATIC_PT_RECTYPE_SEL       1126
#define IDC_STATIC_D5000_DEV_SEL        1128
#define IDC_BUTTON_STOP                 1129
#define IDC_STATIC_D5000_EVENTTYPE_SEL  1130
#define IDC_BUTTON_PLAY                 1131
#define IDC_STATIC_WEATHER_TYPE_SEL     1132
#define IDC_BUTTON_FAST                 1133
#define IDC_STATIC_OP_STATION_SEL       1134
#define IDC_BUTTON_SLOW                 1135
#define IDC_BUTTON_RP_PLANT_SELECT      1136
#define IDC_BTN_SELECT                  1137
#define IDC_LIST_PS_CAMERA_RELATION     1139
#define IDC_LIST_REPLAY_RELATION        1139
#define IDC_RADIO_LOCALPLANT            1140
#define IDC_WEATHER_SHOW                1140
#define IDC_PALYSTATE                   1141
#define IDC_LIST_RELATION               1141
#define IDC_LIST_CAMERA_RELATION        1142
#define IDC_RADIO_REMOTEPLANT           1143
#define IDC_BTN_EXTEND                  1143
#define IDC_SLIDER_PLAYPOS              1144
#define IDC_LIST_HISTORYLOG_SYSTEM      1144
#define IDC_LIST_HISTORYLOG_USER        1145
#define IDC_EDIT_SELECTEDID             1146
#define IDC_STATION_NAME                1147
#define IDC_EDIT_D5000_STATION_SEL      1147
#define IDC_COMBO_HL_TYPE               1147
#define IDC_EDIT_OP_STATION_SEL         1148
#define IDC_COMBO_HL_SUB_TYPE           1148
#define IDC_PALYSPEED                   1149
#define IDC_EDIT_HL_NODE_NAME           1149
#define IDC_COMBO_RECORDTYPE            1151
#define IDC_BUTTON_HL_VIDEO_ERROR       1151
#define IDC_COMBO_D5000_DEV_SEL         1152
#define IDC_LIST_HISTORYLOG_VIDEO_ERROR 1152
#define IDC_MENU_ALARMREALLOG           1153
#define IDC_COMBO_D5000_EVNETTYPE_SEL   1153
#define IDC_CHECK_RELATE_VIDEO          1153
#define IDC_SLIDER_DUIBI                1154
#define IDC_COMBO_WEATHER_TYPE_SEL      1154
#define IDC_CHECK_RELATE_ACCIDENT       1154
#define IDC_STATIC_VIDEO_FLOW           1154
#define IDC_COMBO_D5000_DEV_SEL2        1155
#define IDC_COMBO_D5000_STATION_SEL     1155
#define IDC_CHECK_RELATE_ABNORMAL       1155
#define IDC_SLIDER_BRITE                1156
#define IDC_CHECK_RELATE_NOTIFY         1156
#define IDC_STATIC_WEATHER              1156
#define IDC_FILEPATH                    1157
#define IDC_CHECK_RELATE_METRO_PRE      1157
#define IDC_CHECK_RELATE_METRO_ALARM    1158
#define IDC_EDIT_PROBLEM_CAMERA_NUM     1158
#define IDC_EDIT_STATION_NAME           1158
#define IDC_CHECK_RELATE_TYPHOON_PRE    1159
#define IDC_EDIT_PROBLEM_CAMERA_NUM_500KV 1159
#define IDC_SLIDER_BAOHE                1160
#define IDC_CHECK_RELATE_TYPHOON_ALARM  1160
#define IDC_EDIT_PROBLEM_CAMERA_NUM_220KV 1160
#define IDC_CHECK_RELATE_THUNDER_PRE    1161
#define IDC_EDIT_PROBLEM_CAMERA_NUM_110KV 1161
#define IDC_SLIDER_SEDU                 1162
#define IDC_CHECK_RELATE_THUNDER_ALARM  1162
#define IDC_EDIT_PROBLEM_CAMERA_NUM2    1162
#define IDC_COMBO_PRESET_NAME           1163
#define IDC_CHECK_RELATE_STATE          1163
#define IDC_LIST_PS_RELATION            1164
#define IDC_CHECK_RELATE_SWITCHSTATE    1164
#define IDC_PRESET_SETMOVE              1165
#define IDC_CHECK_RELATE_LIMIT          1165
#define IDC_STATIC_TYPE_SELECT          1166
#define IDC_STATIC_STATION_INFO         1167
#define IDC_BTN_NEXT_PAGE               1168
#define IDC_PRESET_MOVETO               1169
#define IDC_STATIC_PAGE_INFO            1169
#define IDC_STATIC_BRITE                1170
#define IDC_BTN_CANCEL                  1170
#define IDC_BUTTON_CHOOSE_PRESET        1171
#define IDC_EDIT_NEWPRESETNAME          1173
#define IDC_USER_INFO_SHOW              1173
#define IDC_STATIC_DUIBI                1174
#define IDC_MODIFYNAME                  1175
#define IDC_EDIT_HL_RELATION_NODE       1177
#define IDC_STATIC_BAOHE                1178
#define IDC_DATETIMEPICKER_HL_STARTDAY  1179
#define IDC_BTN_MODIFY                  1180
#define IDC_DATETIMEPICKER_HL_STOPDAY   1181
#define IDC_STATIC_SE                   1182
#define IDC_BTN_DEVICE_INFO             1182
#define IDC_DATETIMEPICKER_HL_STARTTIME 1183
#define IDC_TAB_CONTROL                 1184
#define IDC_DATETIMEPICKER_HL_STOPTIME  1185
#define IDC_BTN_ONLINE_RATE_INFO        1185
#define IDC_STATIC_SPEED                1186
#define IDC_EDIT_ALL_CAMERA_NUM         1186
#define IDC_LIST_HISTORYLOG_RELATION    1187
#define IDC_EDIT_CAMERA_ONLINE_RATE     1187
#define IDC_EDIT_OFF_STATION_NUM        1188
#define IDC_STATIC_PRESET               1189
#define IDC_EDIT_ALL_STATION_NUM        1189
#define IDC_BUTTON_HL_CHOOSENODE        1190
#define IDC_EDIT_STATION_ONLINE_RATE    1190
#define IDC_EDIT_ALL_CAMERA_NUM_500KV   1191
#define IDC_BTN_HELP                    1191
#define IDC_EDIT_CAMERA_ONLINE_RATE_500KV 1192
#define IDC_EDIT_OFF_STATION_NUM_500KV  1193
#define IDC_EDIT_CLASS                  1193
#define IDC_EDIT_ALL_STATION_NUM_500KV  1194
#define IDC_TAB_TEST                    1195
#define IDC_EDIT_STATION_ONLINE_RATE_500KV 1195
#define IDC_EDIT_ALL_CAMERA_NUM_220KV   1196
#define IDC_EDIT_CAMERA_ONLINE_RATE_220KV 1197
#define IDC_EDIT_OFF_STATION_NUM_220KV  1198
#define IDC_EDIT_ALL_STATION_NUM_220KV  1199
#define IDC_EDIT_STATION_ONLINE_RATE_220KV 1200
#define IDC_REPLAY                      1201
#define IDC_EDIT_ALL_CAMERA_NUM_110KV   1201
#define IDC_EDIT_CAMERA_ONLINE_RATE_110KV 1202
#define IDC_GETVIEWSET                  1203
#define IDC_EDIT_OFF_STATION_NUM_110KV  1203
#define IDC_EDIT_ALL_STATION_NUM_110KV  1204
#define IDC_EDIT_STATION_ONLINE_RATE_110KV 1205
#define IDC_BUTTON_RS_ADD_SETTIGN       1206
#define IDC_COMBO_TYPE                  1206
#define IDC_EDIT_ALL_CAMERA_NUM2        1207
#define IDC_STATIC_VIDEO_ACCESS_TYPE    1207
#define IDC_EDIT_CAMERA_ONLINE_RATE2    1208
#define IDC_COMBO_VIDEO_ACCESS_TYPE     1208
#define IDC_EDIT_OFF_STATION_NUM2       1209
#define IDC_EDIT_ALL_STATION_NUM2       1210
#define IDC_EDIT_STATION_ONLINE_RATE2   1211
#define IDC_AXISMEDIACONTROL1           1211
#define IDC_EDIT_SEARCH                 1212
#define IDC_BUTTON_SEARCH               1213
#define IDC_VERSION_INFO_SHOW           1214
#define IDC_TREE_DEVICE                 1215
#define IDC_TREE_USER                   1215
#define IDC_PROGRESS1                   1215
#define IDC_PROGRESS_RATE_INFO          1215
#define IDC_BUTTON_SET_TIME             1217
#define IDC_BUTTON_PAUSE_VIDEO          1218
#define IDC_YT_BG                       1219
#define IDC_BUTTON_RESUME_VIDEO         1219
#define IDC_BUTTON_STOP_VIDEO           1220
#define IDC_EDIT_TIME_VALUE             1221
#define IDC_BUTTON_SET                  1222
#define IDC_BUTTON_CANCEL               1223
#define IDC_RADIO_RESUME                1224
#define IDC_SETVIEWSET                  1225
#define IDC_EDIT_PRE                    1225
#define IDC_RADIO_CURRENT               1226
#define IDC_EDIT_CURRENT                1227
#define IDC_COMBO_HL_RELATION_TYPE      1228
#define IDC_RADIO_HEAD                  1228
#define IDC_EDIT_FIRST                  1229
#define IDC_BTN_START                   1230
#define IDC_COMBO_SPEED                 1231
#define IDC_COMBO_HL_RELATION_SUB_TYPE  1232
#define ID_BTN_EXIT                     1233
#define IDC_BUTTON2                     1235
#define IDC_TREE_LIST_SETTING           1236
#define IDC_CAMERA_STATUS_VALUE         1236
#define IDC_MENU_ASSISTANCE             1237
#define IDC_MENU_ALARM                  1238
#define IDC_LIST_REAL_ALARM_INFO        1240
#define IDC_BUTTON_REALTIME_ALARM       1241
#define IDC_BUTTON_PROCESSED_HISTORY    1242
#define IDC_BUTTON_HIDING_ALARM         1243
#define IDC_TIMEINT_SETTING3            1245
#define IDC_BUTTON_PROCESSED_ALARM      1245
#define IDC_BTN_SHOW_ALARM              1246
#define IDC_LIST_DEAL_ALARM_INFO        1247
#define IDC_TREE_LIST_CHOOSE            1248
#define IDC_LIST_LOCAL_DEAL_ALARM_INFO  1248
#define IDC_LIST_LOCAL_HIDE_ALARM_INFO  1249
#define IDC_BUTTON1                     1250
#define IDC_MENU_LINKAGE_SETTING        1250
#define IDC_BUTTON_DEVICE_LEDGER_QUERY  1250
#define IDC_BUTTON_STATION_SELECT       1250
#define IDC_BUTTON_ALARM_SUBSCRIBE_OK   1250
#define IDC_BUTTON_ALARM_SUBSCRIBE      1250
#define IDC_BUTTON_ALARM_REPLAY         1250
#define IDC_BUTTON_ALARM_HISTORY        1250
#define IDC_BUTTON_SEARCHSTATE          1250
#define IDC_BUTTON_UP                   1250
#define IDC_BUTTON_CLOSE                1250
#define IDC_BUTTON_PROCESS_ALL          1250
#define IDC_MENU_DEVICE_LEDGER          1251
#define IDC_LIST_DEVICE_LEDGER          1253
#define IDC_STATIC_DEVICE_LEDGER_STATION 1254
#define IDC_BUTTON_SELECT_STATION       1255
#define IDC_YT_LOCK                     1256
#define IDC_TREE_STATION_SELECT_LIST    1256
#define IDC_BUTTON_CHOOSEYT             1257
#define IDC_EDIT_STATION_SELECT         1257
#define IDC_BUTTON_CHOOSEVIEW           1258
#define IDC_BUTTON_DEVICE_LEDGER_STATISTICAL 1258
#define IDC_BUTTON_DEVICE_LEDGER_EXPORT 1259
#define IDC_TREE_ALARM_SUBSCRIBE_STATION 1260
#define IDC_LIST_ALARM_SUBSCRIBE        1261
#define IDC_BUTTON_ALARM_SUBSCRIBE_CANCEL 1262
#define IDC_EDIT_ALARM_REPLAY_STATION   1264
#define IDC_STATIC_ALARM_STATION        1265
#define IDC_STATIC_ALARM_DEVICE         1266
#define IDC_COMBO_ALARM_DEVICE          1267
#define IDC_BUTTON_ALARM_SELECT         1268
#define IDC_EDIT_STATION                1269
#define IDC_COMBO_DEVICE                1270
#define IDC_BUTTON_PS_VIEWLIST          1272
#define IDC_BUTTON_PS_RELATIONLIST      1273
#define IDC_LIST_ALARM_LOG              1273
#define IDC_BTN_SHOW_CONTROL            1274
#define IDC_BTN_SHOW_HIDE               1276
#define IDC_BUTTON_HL_CHOOSE_STATION    1276
#define IDC_STATIC_PT_NODESEL           1277
#define IDC_BUTTON_HL_DEVICE            1277
#define IDC_STATIC_D5000_STATION_SEL    1278
#define IDC_DATETIMEPICKER_STARTDAY     1280
#define IDC_DATETIMEPICKER_STARTTIME    1281
#define IDC_DATETIMEPICKER_STOPDAY      1282
#define IDC_DATETIMEPICKER_STOPTIME     1283
#define IDC_LIST_HL_DEVICE              1284
#define IDC_STATIC_DIAGNOSIS_INFO       1285
#define IDC_MENU_ELECMAP                1286
#define IDC_TREE_ELECMAP                1287
#define IDC_LIST_REAL_EX_ALARM_INFO     1287
#define IDC_EDIT1                       1288
#define IDC_EDIT_SEARCHSTATE            1288
#define IDC_BUTTON_REALTIME_EX_ALARM    1288
#define IDC_LIST_LINKAGE_ACTION         1289
#define IDC_BUTTON_LINKAGE              1290
#define IDC_BUTTON_LINKAGE_CONFIG       1291
#define IDC_COMBO_LINKAGE_SHOW_TYPE     1292
#define IDC_COMBO_SHOW_VIDEO            1293
#define IDC_COMBO_CHANGE_TIME           1294
#define IDC_CHECK_SECURITY              1295
#define IDC_CHECK_FIRE                  1296
#define IDC_CHECK_DOOR_ALARM            1297
#define IDC_CHECK4                      1298
#define IDC_CHECK_DOOR_ACTION           1298
#define IDC_CHECK_DOOR                  1298
#define IDC_STATIC_LINKAGE_SHOW_TYPE    1299
#define IDC_STATIC_SHOW_VIDEO           1300
#define IDC_STATIC_CHANGE_TIME          1301
#define IDC_STATIC_LINKAGE_DATA_SOURCE  1302
#define IDC_GROUP_LINKAGE_DATA_SOURCE   1303
#define IDC_BUTTON_RIGHT                1304
#define IDC_BUTTON_LOCK                 1305
#define IDC_BUTTON_DOWN                 1306
#define IDC_BUTTON_ZOOM_IN              1307
#define IDC_BUTTON_ZOOM_OUT             1308
#define IDC_STATIC_CAMERA               1310
#define IDC_STATIC_ALARM_INFO           1311
#define IDC_BUTTON_LEFT                 1312
#define IDC_TREE1                       1314
#define IDC_DEVICE_LEDGER_STATION_TREE  1314
#define IDC_TREE_STATION                1314
#define IDC_COMBO1                      1315
#define IDC_COMBO_CAMERA                1315
#define IDC_BUTTON_ALARM_STATISTICS     1319
#define IDC_LIST_ALARM_STATISTICS       1320
#define IDC_BUTTON_ALARM_PREVIEW        1321
#define IDC_LIST_ALARM                  1322
#define IDC_CHECK_ALL                   1328
#define IDC_CHECK3                      1334
#define IDC_CHECK_DOOR1                 1334
#define IDC_CHECK_ANFANG                1335
#define IDC_CHECK_ANFANG1               1335
#define IDC_CHECK_FIRE1                 1336
#define IDC_STATIC_KUANG                1338
#define ID_MENUITEM_REFLASHLIST         32772
#define ID_MENUITEMEXITVIDEO            32780
#define ID_MENUITEMSTARTREC             32781
#define ID_MENUITEMSTOPREC              32782
#define ID_MENUITEMCAPTURE              32783
#define ID_MENUITEM_MULTIFULLS          32784
#define ID_MENUITEM_EXITMULTIFULLS      32785
#define IDM_MAPINTHESUBSTATION          32789
#define IDM_POINTVIDEO                  32790
#define ID_MENUITEM_MAPEXITVIDEO        32792
#define ID_MENUITEM_DELETEFAVORITE      32795
#define ID_MENUITEM_PLAYTOMAIN          32796
#define ID__32797                       32797
#define ID__32798                       32798
#define ID_MENU_START_TUNECYCLE         32802
#define ID_MENU_STOP_TUNECYCLE          32804
#define ID_MENU_STOP_ALL_VIDEO          32806
#define ID_MENU_ITEM_SHOW               32809
#define ID_MENU_ITEM_EXIT               32810
#define ID_MENU_VIDEO_REPLAY_DOWNLOAD   32813
#define ID_MENU_VIDEO_REPLAY_PLAY       32814
#define ID_MENUITEM_TAGCAMERA           32816
#define ID_MENUITEM_CANCEL_CAMERA_TAG   32818
#define ID_MENUITEM_TAG_CAMERA          32820
#define ID_MENUITEM_OPEN_STATION_CAMERA_VIDEO 32822
#define ID_ITEM_MENU_CANCELCAMERA       32825
#define ID_MENUITEM_CANCELCAMERA        32826
#define ID_MENUITEM_TAG_CLASS           32829
#define ID_MENUITEM_SELECT_DEVICE_REFLASHLIST 32831
#define ID_MENUITEM_BY_VOLTAGE          32833
#define ID_MENUITEM_BY_CITY             32835
#define ID__32836                       32836
#define ID_MENUITEM_OPEN_STATION_CAMERA_VIDEO_AUTO 32837
#define ID__32838                       32838
#define ID__MENUITEM                    32839
#define ID__MENUITEM_VIEW_CAMERA_STATUS 32840
#define ID__32841                       32841
#define ID__32842                       32842
#define ID_MENUITEM_SET_ANFANG_CAMERA   32843
#define ID_MENUITEM_UNSET_ANFANG_CAMERA 32844
#define ID_MENUITEM_CANCEL_ANFANG_CAMERA 32845
#define ID__32846                       32846
#define ID__32847                       32847
#define ID_MENUITEM_SHOW_ALL_CAMERA     32848
#define ID_MENUITEM_ONLY_SHOW_ANFANG_CAMERA 32849
#define IDB_BITMAP_BG_BOTTOMCENTER      58116

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        489
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         1339
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
