//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LinkageSetting.rc
//
#define IDB_BITMAP_TITLE                2006
#define IDB_BITMAP_VIDEO_BG             2007
#define IDC_CURSOR_YTDOWN               2008
#define IDC_CURSOR_YTDOWN_ON            2009
#define IDC_CURSOR_YTLEFT               2010
#define IDC_CURSOR_YTLEFT_ON            2011
#define IDC_CURSOR_YTRIGHT              2014
#define IDC_CURSOR_YTRIGHT_ON           2015
#define IDC_CURSOR_YTUP                 2016
#define IDC_CURSOR_YTUP_ON              2017
#define IDD_DIALOG_PTU                  4000
#define IDD_DIALOG_PRESET_SETTING       4001
#define IDC_BUTTON_PRESET_CONFIG        4001
#define IDB_BITMAP_TREE                 4002
#define IDC_TREE_STATION_LIST           4003
#define IDR_MENU_CLOSE_VIDEO            4003
#define IDD_DIALOG_PTU_MANAGE           4004
#define IDC_TREE_LINKAGE_LIST           4005
#define IDR_MENU_PTU_TREELIST           4005
#define IDC_TREE_PRESETTING_LIST        4006
#define IDB_BITMAP_BG                   4006
#define IDC_EDIT_PRESET_NAME            4007
#define IDB_BITMAP_BACK                 4007
#define IDC_COMBO_PRESET_NUM            4008
#define IDB_BITMAP_INTERVAL             4008
#define IDD_DIALOG_DEVICE_LEDGER        4009
#define IDD_DIALOG_ADD_DEVICE_LEDGER    4010
#define IDD_DIALOG_LINKAGE_CONFIG       4011
#define IDC_BUTTON_UP                   4012
#define IDD_DIALOG_ADD_LINKAGE_DEV      4012
#define IDC_BUTTON_DOWN                 4013
#define IDD_DIALOG_DEVICE_TYPE_CONFIG   4013
#define IDC_BUTTON_LEFT                 4014
#define IDD_DIALOG_VIEW_OUT             4014
#define IDC_BUTTON_RIGHT                4015
#define IDC_BUTTON_LOCK                 4016
#define IDC_BUTTON_ZOOM_IN              4017
#define IDC_BUTTON_ZOOM_OUT             4018
#define IDC_STATIC_LINKAGE_LIST         4019
#define IDC_STATIC_PRESET_LIST          4020
#define IDC_STATIC_PRESET_NUM           4021
#define IDC_STATIC_PRESET_NAME          4022
#define IDC_BUTTON_SET_PRESET           4023
#define IDC_BUTTON_DELETE_PRESET        4024
#define IDC_BUTTON_TO_PRESET            4025
#define IDR_HTML_DLGADDLINKAGEDEV       4026
#define IDC_BUTTON_PTU_CONFIG           4027
#define IDC_EDIT_PTU_IP                 4028
#define IDC_EDIT_PTU_PORT               4029
#define IDC_EDIT_PTU_USERNAME           4030
#define IDC_EDIT_PTU_PASSWORD           4031
#define IDC_STATIC_PTU_IP               4032
#define IDC_STATIC_PTU_PORT             4033
#define IDC_STATIC_PTU_USERNAME         4034
#define IDC_STATIC_PTU_PASSWORD         4035
#define IDC_BUTTON_CHANGE_INFO          4036
#define IDC_BUTTON_CONNECT_TEST         4037
#define IDC_BUTTON_GET_DEVICE_INFO      4038
#define IDC_STATIC_PTU_STATUS           4039
#define IDC_STATIC_PTU_STATUS_VALUE     4040
#define IDC_TREE_RVU_DEVICE_LIST        4041
#define IDC_TREE_ROUTE_RVU_DEVICE_LIST  4042
#define IDC_BUTTON_ADD_TO_LOCAL_DATABASE 4043
#define IDC_STATIC_LOCAL_DEVICE         4044
#define IDC_STATIC_ROUTE_DEVICE         4045
#define IDC_STATIC_PTU_NAME             4046
#define IDC_EDIT_PTU_NAME               4047
#define IDC_TREE_SUB_SYSTEM_LIST        4048
#define IDC_STATIC_SUB_SYSTEM           4049
#define IDC_STATIC_GROUP_BOX            4050
#define IDC_STATIC_STATION_LIST         4051
#define IDC_BUTTON_DEL_RVU              4052
#define IDC_LIST_LINKAGE_RELATION       4053
#define IDC_STATIC_LINKAGE_RELATION     4054
#define IDC_TREE_DEVICE_LIST            4055
#define IDC_EDIT_DEVICE_MANUFACTURE     4056
#define IDC_EDIT_DEVICE_IP              4057
#define IDC_EDIT_DEVICE_PORT            4059
#define IDC_EDIT_LOGIN_USERNAME         4060
#define IDC_EDIT_LOGIN_PASSWORD         4061
#define IDC_EDIT_PROTOCOL_TYPE          4062
#define IDC_EDIT_DEVICE_TYPE            4063
#define IDC_EDIT_HARDDISK_CAPACITY      4064
#define IDC_EDIT_ANOLOG_VIDEO_NUM       4065
#define IDC_EDIT_NET_VIDEO_NUM          4066
#define IDC_BUTTON_ADD_DEVICE           4067
#define IDC_BUTTON_EDIT_DEVICE          4068
#define IDC_BUTTON_DEL_DEVICE           4069
#define IDC_STATIC_DEVICE_MANUFACTURE   4070
#define IDC_STATIC_PROTOCOL_TYPE        4071
#define IDC_STATIC_DEVICE_MANUFACTURE_IDENTIFY 4072
#define IDC_STATIC_PROTOCOL_TYPE_IDENTIFY 4073
#define IDC_STATIC_DEVICE_IP            4074
#define IDC_STATIC_DEVICE_IP_IDENTIFY   4075
#define IDC_STATIC_DEVICE_PORT          4076
#define IDC_STATIC_DEVICE_PORT_IDENTIFY 4077
#define IDC_STATIC_LOGIN_USERNANME      4078
#define IDC_STATIC_LOGIN_USERNAME_IDENTIFY 4079
#define IDC_STATIC_LOGIN_PASSWORD       4080
#define IDC_STATIC_LOGIN_PASSWORD_IDENTIFY 4081
#define IDC_STATIC_DEVICE_TYPE          4082
#define IDC_STATIC_HARDDISK_CAPACITY    4083
#define IDC_STATIC_ANOLOG_VIDEO_NUM     4084
#define IDC_STATIC_NET_VIDEO_NUM        4085
#define IDC_BUTTON_DEVICE_LEDGER_MANAGE 4086
#define IDC_STATIC_DEVICE_LIST          4087
#define IDC_EDIT_DEV_NAME               4088
#define IDC_EDIT_DEV_IP                 4089
#define IDC_COMBO_DEV_FACTORY_NAME      4090
#define IDC_EDIT_DEV_PORT               4091
#define IDC_EDIT_DEV_USER               4092
#define IDC_EDIT_DEV_PASSWORD           4093
#define IDC_EDIT_DEV_PROTOCOL           4094
#define IDC_EDIT_DEV_TYPE               4095
#define IDC_EDIT1                       4095
#define IDC_EDIT_DEVICE_NAME            4095
#define IDC_EDIT_CURRENT_CAMERA         4095
#define IDC_EDIT_RVU_CODE               4095
#define IDC_EDIT_SEARCH                 4095
#define IDC_EDIT_DEV_HARDDISK           4096
#define IDC_STATIC_DEVICE_NAME          4096
#define IDC_EDIT_DEV_AV_NUM             4097
#define IDC_BUTTON1                     4097
#define IDC_BUTTON_EDIT_RVU             4097
#define IDC_BUTTON_ADD_LINKAGE_DEV      4097
#define IDC_BUTTON_LINKAGE_CONFIG       4097
#define IDC_EDIT_DV_NUM                 4098
#define IDC_TREE_DEV                    4098
#define IDC_LIST_LINKAGE                4099
#define IDC_STATIC_DEV_TREE             4100
#define IDC_COMBO_LINKAGE_TYPE          4102
#define IDC_COMBO_LINKAGE_DEV_NAME      4103
#define IDC_COMBO_LINKAGE_ACTION        4104
#define IDC_LIST_DEVICE_LEDGER          4106
#define IDC_EDIT2                       4107
#define IDC_EDIT_CURRENT_DEVICE         4107
#define IDC_STATIC_CURRENT_CAMERA       4108
#define IDC_STATIC_CURRENT_DEVICE       4109
#define IDC_BUTTON_DEVICE_TYPE_CONFIG   4112
#define IDC_COMBO_RVU_TYPE              4113
#define IDC_STATIC_RVU_TYPE             4114
#define IDC_STATIC_PICTURE              4115
#define IDC_STATIC_RVU_CODE             4116
#define IDC_BUTTON2                     4117
#define IDC_BUTTON_SEARCH               4117
#define ID__32771                       32771
#define ID_CLOSE_VIDEO                  32772
#define ID__32773                       32773
#define ID_MENU_VIEW_PTU_INFO           32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4015
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         4118
#define _APS_NEXT_SYMED_VALUE           4059
#endif
#endif
